FROM base_aflplusplus
ENV FUZZER_NAME="AFLplusplus llvm_mode + laf-passes (afl-clang-fast)"

ENV LAF_SPLIT_SWITCHES=1
ENV LAF_TRANSFORM_COMPARES=1
ENV LAF_SPLIT_COMPARES=1

ENV CC afl-clang-fast
ENV AFL_FLAGS ""
